apiVersion: v1
kind: Service
metadata:
  name: movie-service
  namespace: movie-ns
spec:
  type: NodePort
  selector:
    app: movie
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 30007
